apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: flask-k3s:1.0
          ports:
            - containerPort: 5000
          env:
            - name: VERSION
              value: "1.0"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
