name: Deploy to Local K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test cluster
        run: kubectl get nodes

      - name: Deploy
        run: kubectl apply -f k8s/
